<?php

/**
 * @file
 * Primary module hooks for Cloner module.
 */

/**
 * Implements hook_entity_type_alter().
 */
function cloner_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityType[] $entity_types */
  foreach ($entity_types as $entity_type_id => $entity_type) {
    $entity_type->setLinkTemplate('cloner-form', "/cloner/$entity_type_id/{{$entity_type_id}}");
  }
}
