<?php declare(strict_types = 1);

/**
 * @file
 * Primary module hooks for Cloner module.
 */

use Drupal\cloner\Hook\Entity\EntityOperation;
use Drupal\cloner\Hook\Entity\EntityTypeAlter;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_type_alter().
 */
function cloner_entity_type_alter(array &$entity_types): void {
  \Drupal::classResolver(EntityTypeAlter::class)($entity_types);
}

/**
 * Implements hook_entity_operation().
 */
function cloner_entity_operation(EntityInterface $entity): array {
  return \Drupal::classResolver(EntityOperation::class)($entity);
}
