<?php declare(strict_types = 1);

/**
 * @file
 * Main file for hooks and functions.
 */

use Drupal\cloner_examples\Hook\Form\NodeArticleEditFormAlter;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter() for node_article_edit_form.
 */
function cloner_examples_form_node_article_edit_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  \Drupal::classResolver(NodeArticleEditFormAlter::class)($form, $form_state, $form_id);
}
